validation:
  content: 500
  name: 255
  description: 500
  quantity: 0
  address: 255
  full_name: 255
  phone: 15
  point: 0
  price: 0
  email: 255
  password: 6
  user_name_max: 15
  user_name_min: 3
  picture_size: 400
image:
  avatar_size: "250x250"
  size_thumbnail: "80x80"
recently_viewed:
  per_page: 10
  cookie_size: 20
login_page:
  checked: "1"
product:
  products_per_page: 10
